version: '3.8'

services:
  beacon:
    image: ghcr.io/Kaonashie/beacon:latest  # Replace 'your-username' with your GitHub username
    container_name: beacon
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "http.get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Alternative: Build locally instead of using pre-built image
  # Uncomment this section and comment out the above if you want to build locally
  # beacon:
  #   build: .
  #   container_name: beacon
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - NODE_ENV=production
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./data:/app/data
  #     - ./logs:/app/logs